# Generated by Django 5.2.1 on 2025-05-18 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_daily_parent_daily_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={},
        ),
        migrations.AddField(
            model_name='longterm',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='time_needed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_needed'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='time_todo',
            field=models.DateTimeField(null=True, verbose_name='time_todo'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='longterm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthly',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='time_needed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_needed'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='time_todo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time_todo'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekly',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='time_needed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_needed'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='time_todo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time_todo'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='weekly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearly',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='time_needed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_needed'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='time_todo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time_todo'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='yearly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daily',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time_needed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_needed'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time_todo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time_todo'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterModelTable(
            name='daily',
            table=None,
        ),
    ]
