# Generated by Django 5.2.1 on 2025-05-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_daily_options_longterm_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name': 'daily'},
        ),
        migrations.AlterModelTable(
            name='daily',
            table='daily',
        ),
    ]
