# Generated by Django 5.2.1 on 2025-05-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_daily_options_alter_daily_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={},
        ),
        migrations.AlterModelTable(
            name='daily',
            table=None,
        ),
    ]
